version: '3'
services:
  web:
    build: .
    volumes:
      - .:/vapor
    ports:
      - "3000:3000"
  environment:
    cloudantUrl: ""
    searchIndex: ""
    githubAccessToken: ""
    githubUsername: ""

